package config

import (
	"fmt"
	"strings"
)

type ConfigTemplate struct {
	BaseDomain string
	Endpoint   string
	WGAddress  string
	VMSubnet   string
}

func RenderExample(t ConfigTemplate) string {
	if t.BaseDomain == "" {
		t.BaseDomain = "dev.example.com"
	}
	if t.Endpoint == "" {
		t.Endpoint = "YOUR_SERVER_PUBLIC_IP_OR_DNS:51820"
	}
	if t.WGAddress == "" {
		t.WGAddress = "10.77.0.1/24"
	}
	if t.VMSubnet == "" {
		t.VMSubnet = "10.88.0.0/16"
	}
	baseDomainComment := ""
	if t.BaseDomain == "dev.example.com" {
		baseDomainComment = "# EDIT PLACEHOLDER\n"
	}
	endpointComment := ""
	if strings.Contains(t.Endpoint, "YOUR_SERVER_PUBLIC_IP_OR_DNS") {
		endpointComment = "# EDIT PLACEHOLDER\n"
	}
	return fmt.Sprintf(`# Example firedoze host configuration.
#
# Generated by firedozed -init-config. If any placeholder values remain,
# edit them before starting firedozed. Placeholder values are marked with:
# EDIT PLACEHOLDER

%sbase_domain = %q
default_http_port = 8080
state_dir = "/var/lib/firedoze"

[api]
port = 8081

[caddy]
http_port = 80
https_port = 443
internal_proxy_port = 18082

[dns]
port = 53

[metadata]
path = "/var/lib/firedoze/firedoze.db"

[wireguard]
interface = "fdwg0"
listen_port = 51820
address = %q
%sendpoint = %q
private_key_file = "/etc/firedoze/wg.key"

# Add one peer for each laptop that should administer firedoze.
# Each peer needs a unique /32 address inside the WireGuard subnet.
#
# firedozed -wg-add-peer alice-laptop ALICE_PUBLIC_KEY appends the peer block
# automatically and prints a client config with a private-key placeholder.

[vm_network]
# Private IPv4 range used for VM addresses. Change it if it overlaps with
# your WireGuard subnet, VPC, LAN, or VPN routes.
subnet = %q

[ssh]
user = "ubuntu"
authorized_key_files = ["/etc/firedoze/authorized_keys"]
# Private SSH wake proxy port on the firedoze host. The firedoze client uses
# this to wake sleeping VMs before handing the connection to the guest SSH port.
wake_proxy_port = 18022

[idle]
check_interval_seconds = 30
default_sleep_after_seconds = 1800

[firecracker]
binary_path = "/usr/local/bin/firecracker"
base_kernel_path = "/var/lib/firedoze/images/vmlinux.bin"
base_initrd_path = "/var/lib/firedoze/images/initrd.img"
base_rootfs_path = "/var/lib/firedoze/images/rootfs.ext4"
default_vcpus = 1
default_memory_mib = 512
default_disk_bytes = 4294967296
`, baseDomainComment, t.BaseDomain, t.WGAddress, endpointComment, t.Endpoint, t.VMSubnet)
}
